### ISSUE TITLE
Gettext 0.15.0 breaks support for elixir v1.3.4

### ISSUE THREAD

**Issue by hazardfn** [bitwalker/timex#413]
### Steps to reproduce

Try to compile using Elixir 1.3.4 (after removing/updating your current lock file).

```
== Compilation error on file lib/l10n/gettext.ex ==
** (UndefinedFunctionError) function Enum.split_with/2 is undefined or private. Did you mean one of:

      * split/2
      * split_while/2

    (elixir) Enum.split_with(["# # `msgid`s in this file come from POT (.pot) files.", "# #", "# # Do not add, change, or remove `msgid`s manually here as", "# # they're tied to the ones in the corresponding POT file", "# # (with the same domain).", "# #", "# # Use `mix gettext.extract --merge` or `mix gettext.merge`", "# # to merge POT files into PO files."], #Function<3.59487184/1 in Gettext.PO.Parser.extract_references/1>)
    (gettext) lib/gettext/po/parser.ex:51: Gettext.PO.Parser.extract_references/1
    (gettext) lib/gettext/po/parser.ex:34: Gettext.PO.Parser.to_struct/1
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (gettext) lib/gettext/po/parser.ex:24: Gettext.PO.Parser.parse_yecc_result/1
    (gettext) lib/gettext/po.ex:64: Gettext.PO.parse_string/1
    (gettext) lib/gettext/po.ex:126: Gettext.PO.parse_file/1
    (gettext) lib/gettext/po.ex:147: Gettext.PO.parse_file!/1

could not compile dependency :timex, "mix compile" failed. You can recompile this dependency with "mix deps.compile timex", update it with "mix deps.update timex" or clean it with "mix deps.clean timex"
make: *** [deps] Error 1
```

### Description of issue

It seems the current version constraint for gettext in Timex's mix.exs makes 0.15.0 a valid candidate which supports `~> 1.4` conflicting with Timex's mix file which states `~> 1.3`

The problem comes from gettext's use of `split_with/2`.

_Running `mix deps.update --all` as a before_script would spot potential constraint errors_

### Workaround

If you are here because you have the same problem just override gettext in your mix file:

`{:gettext, "~> 0.14.1", override: true}`

**Comment by bitwalker** [comment]
I will probably retire this release since it is broken, and bump to `3.2.0` along with a new Elixir version requirement of 1.4. I'll leave this open until I've made that change. Thanks for reporting!

**Comment by bitwalker** [comment]
I've retired 3.1.25 (that means this version can be used if you previously depended on it, but you will get a warning, but no new dependencies on this version can be formed). Version 3.2.0 has been published with a new Elixir version requirement of `~> 1.4` and a formatting bug fix.
